local DISABLE_RECIPES_PORKLAND = {
	"transmute_marble",
	"transmute_cutstone",
	"transmute_moonrocknugget",
	"transmute_beefalowool",
}

local ENABLE_RECIPES_PORKLAND = {
    "farm_hoe",
    "golden_farm_hoe",
    "farm_plow_item",
    "wateringcan",
    "soil_amender",
    "compostingbin",
    "plantregistryhat",
    "phonograph",
    "record",
    "trophyscale_oversizedveggies",
    "seedpouch",
    "sewing_mannequin",
    "punchingbag",
    "goggleshat",
    "sweatervest",
    "moondial",
    "slow_farmplot",
    "fast_farmplot",
    "sculptingtable",
}

local LOST_RECIPES_FOREST = {
    "trusty_shooter",
    "wheeler_tracker",
    "disarming_kit",
    "ballpein_hammer",
    "goldpan",
    "magnifying_glass",
    "smelter",
    "corkchest",
    "roottrunk",
    "basefan",
    "bugrepellent",
    "machete",
    "goldenmachete",
    "shears",
    "antler",
    "antler_corrupted",
    "blunderbuss",
    "cork_bat",
    "halberd",
    "metalplatehat",
    "armor_metalplate",
    "armor_weevole",
    "armorvortexcloak",
    "living_artifact",
    "antmaskhat",
    "antsuit",
    "bathat",
    "candlehat",
    "snakeskinhat",
    "armor_snakeskin",
    "gasmaskhat",
    "thunderhat",
    "pithhat",
    "hogusporkusator",
    "bonestaff",
    "ox_flute",
    "goldnugget",
    "clawpalmtree_sapling_item",
    "venomgland",
    "fabric",
    "turf_lawn",
    "turf_fields",
    "turf_deeprainforest_nocanopy",
    "boat_lograft",
    "boat_row",
    "boat_cork",
    "boat_cargo",
    "boatrepairkit",
    "boat_torch",
    "sail_snakeskin",
    "trawlnet",
    "disguisehat",
    "poisonbalm",
    "sprinkler",
    "slow_farmplot",
    "fast_farmplot",
    "tuber_tree_sapling_item",
}

local PIGSHOPLIST = {
    "city_lamp",
    "pighouse_city",
    "pig_shop_deli",
    "pig_shop_general",
    "pig_shop_hoofspa",
    "pig_shop_produce",
    "pig_shop_florist",
    "pig_shop_academy",
    "pig_shop_antiquities",
    "pig_shop_arcane",
    "pig_shop_weapons",
    "pig_shop_hatshop",
    "pig_shop_bank",
    "pig_shop_tinker",
    "pig_shop_cityhall_player",
    "pig_guard_tower",
    "playerhouse_city",
    "skyworthy_shop",
    "pig_shop_skyworthy",
}

return {
    ENABLE_RECIPES_PORKLAND = ENABLE_RECIPES_PORKLAND,
    DISABLE_RECIPES_PORKLAND = DISABLE_RECIPES_PORKLAND,
    LOST_RECIPES_FOREST = LOST_RECIPES_FOREST,
    PIGSHOPLIST = PIGSHOPLIST,
}
