GLOBAL.setfenv(1, GLOBAL)

local CHARACTERS = STRINGS.CHARACTERS

local function AutoSet(tab)
	tab.DESCRIBE.WX78MODULE_PORKLANDREBALANCE_FAN = tab.DESCRIBE.WX78MODULE_PORKLANDREBALANCE_FAN or tab.DESCRIBE.WX78MODULE_MAXHEALTH
	tab.DESCRIBE.WX78MODULE_PORKLANDREBALANCE_FILTER = tab.DESCRIBE.WX78MODULE_PORKLANDREBALANCE_FILTER or tab.DESCRIBE.WX78MODULE_MAXHEALTH
	tab.DESCRIBE.DUMBBELL_IRON = tab.DESCRIBE.DUMBBELL_IRON or tab.DESCRIBE.DUMBBELL
end

for k, v in pairs(CHARACTERS) do
	AutoSet(v)
end