local GetModConfigData = GetModConfigData
GLOBAL.setfenv(1, GLOBAL)

PL_CONFIG = {
    PUGALISK_HP_MULTIPLIER = GetModConfigData("PUGALISK_HP_MULTIPLIER"),
    ANCIENT_HERALD_HP_MULTIPLIER = GetModConfigData("ANCIENT_HERALD_HP_MULTIPLIER"),
    ANCIENT_HULK_HP_MULTIPLIER = GetModConfigData("ANCIENT_HULK_HP_MULTIPLIER"),
    ANTQUEEN_HP_MULTIPLIER = GetModConfigData("ANTQUEEN_HP_MULTIPLIER"),
    ENABLE_SKILLTREE = GetModConfigData("ENABLE_SKILLTREE"),
    ENABLE_TERRARIUM = GetModConfigData("ENABLE_TERRARIUM"),
    ENABLE_TOUCHSTONE = GetModConfigData("ENABLE_TOUCHSTONE"),
    ENABLE_CRITTERLAB = GetModConfigData("ENABLE_CRITTERLAB"),
    APORKALYPSE_PERIOD_LENGTH = GetModConfigData("APORKALYPSE_PERIOD_LENGTH"),
    ENABLE_SKYWORTHY = GetModConfigData("ENABLE_SKYWORTHY"),
}

PL_WORLDTYPE = { -- 键对应它们的levels.location的大写，值对应世界tag的大写
    FOREST = "FOREST",
    CAVE = "CAVE",
    SHIPWRECKED = "ISLAND",
    VOLCANOWORLD = "VOLCANO",
    PORKLAND = "PORKLAND",
    UNKNOWN = "UNKNOWN",
}
