local function _Translator(string)
	return string["EN"]
end

return {
	DESCRIBE = {
		SEEDOFRUIN = _Translator({EN = "WILBA BRINGE'TH BACK THE PAST!", CN = "我将带你回到过去!"}),
		SKYWORTHY = _Translator({EN = "THAT WAY MADNESS LIES", CN = "这样疯狂的谎言"}),
		SKYWORTHY_KIT = _Translator({EN = "THAT WAY MADNESS LIES", CN = "这样疯狂的谎言"}),
		SHOPLOCKER = _Translator({EN = "STOCK THESE, WILBA BESEECHETH THEE!", CN = "备齐此货，威尔巴恳请阁下！"}),
	},
}
--[[
STRINGS.ACTIONS.PORKLANDREBALANCE_REPICK = "Reincarnate"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.VORTEXEYE = "I..I don't feel so good.."
STRINGS.CHARACTERS.WILSON.DESCRIBE.VORTEXEYE = "A familiar presence?"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.VORTEXEYE = "It's cold..too cold..."
STRINGS.CHARACTERS.WENDY.DESCRIBE.VORTEXEYE = "Will this take me to Abigail?"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.VORTEXEYE = "Wolfgang does not like spooky eye."
STRINGS.CHARACTERS.WX78.DESCRIBE.VORTEXEYE = "ERROR: CANNOT PERCEIVE THROUGH THE BEYOND."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.VORTEXEYE = "This trinket somehow reminds me of the post-Vedic myths of Samsara."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.VORTEXEYE = "It looks cold, eh, Lucy?"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.VORTEXEYE = "No doubt the work of Them."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.VORTEXEYE = "The maw of Hel."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.VORTEXEYE = "It's so cold inside!"
STRINGS.CHARACTERS.WARLY.DESCRIBE.VORTEXEYE = "Maman..."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.VORTEXEYE = "So cold."
STRINGS.CHARACTERS.WINONA.DESCRIBE.VORTEXEYE = "C-charlie? Are you there?"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.VORTEXEYE = "Hyuyu! To another adventure!"
STRINGS.CHARACTERS.WALTER.DESCRIBE.VORTEXEYE = "Yeeeep. It's cursed."
STRINGS.CHARACTERS.WURT.DESCRIBE.VORTEXEYE = "Feel weeeeeeeeeeeeak..."
STRINGS.CHARACTERS.WANDA.DESCRIBE.VORTEXEYE = "It's time for Them to take me, isn't it?"]]--