GLOBAL.setfenv(1, GLOBAL)

return {
	DESCRIBE = {
		SEEDOFRUIN = en_zh({EN = "Glowy seed", CN = "有光泽的种子"}),
		SKYWORTHY = en_zh({EN = "Where to?", CN = "去哪?"}),
		SKYWORTHY_KIT = en_zh({EN = "Where to?", CN = "去哪?"}),
		FROGFISHBOWL_HAMLET = en_zh({EN = "Yum yums!", CN = "好吃!"}),
		ALOE_OVERSIZED = en_zh({EN = "Clumpy Friend", CN = "成块的朋友"}),
		RADISH_OVERSIZED = en_zh({EN = "Red Balls For Belly", CN = "肚子里的红球"}),
		SHOPLOCKER = en_zh({EN = "Sell more.", CN = "多卖点这个东西！"}),
	},
}
--[[
STRINGS.ACTIONS.PORKLANDREBALANCE_REPICK = "Reincarnate"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.VORTEXEYE = "I..I don't feel so good.."
STRINGS.CHARACTERS.WILSON.DESCRIBE.VORTEXEYE = "A familiar presence?"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.VORTEXEYE = "It's cold..too cold..."
STRINGS.CHARACTERS.WENDY.DESCRIBE.VORTEXEYE = "Will this take me to Abigail?"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.VORTEXEYE = "Wolfgang does not like spooky eye."
STRINGS.CHARACTERS.WX78.DESCRIBE.VORTEXEYE = "ERROR: CANNOT PERCEIVE THROUGH THE BEYOND."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.VORTEXEYE = "This trinket somehow reminds me of the post-Vedic myths of Samsara."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.VORTEXEYE = "It looks cold, eh, Lucy?"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.VORTEXEYE = "No doubt the work of Them."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.VORTEXEYE = "The maw of Hel."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.VORTEXEYE = "It's so cold inside!"
STRINGS.CHARACTERS.WARLY.DESCRIBE.VORTEXEYE = "Maman..."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.VORTEXEYE = "So cold."
STRINGS.CHARACTERS.WINONA.DESCRIBE.VORTEXEYE = "C-charlie? Are you there?"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.VORTEXEYE = "Hyuyu! To another adventure!"
STRINGS.CHARACTERS.WALTER.DESCRIBE.VORTEXEYE = "Yeeeep. It's cursed."
STRINGS.CHARACTERS.WURT.DESCRIBE.VORTEXEYE = "Feel weeeeeeeeeeeeak..."
STRINGS.CHARACTERS.WANDA.DESCRIBE.VORTEXEYE = "It's time for Them to take me, isn't it?"]]--