GLOBAL.setfenv(1, GLOBAL)

return {
	DESCRIBE = {
		WX78MODULE_PORKLANDREBALANCE_FAN = en_zh({EN = "EVEN THE WATER MIST CANNOT HARM ME", CN = "即使是水雾也伤害不了我"}),
		WX78MODULE_PORKLANDREBALANCE_FILTER = en_zh({EN = "PARTICULATE OBLITERATOR", CN = "微粒阻断剂"}),
		SEEDOFRUIN = en_zh({EN = "PREHISTORICAL RECOMBINATOR", CN = "史前重组器"}),
		SKYWORTHY = en_zh({EN = "EXIT PORT", CN = "出口"}),
		SKYWORTHY_KIT = en_zh({EN = "EXIT PORT", CN = "出口"}),
		FROGFISHBOWL_HAMLET = en_zh({EN = "MY MINION IS VERY USEFUL", CN = "我的仆从很有用"}),
		ALOE_OVERSIZED = en_zh({EN = "GREEN ENERGY ACQUIRED", CN = "获得绿色能源"}),
		RADISH_OVERSIZED = en_zh({EN = "RED SPHERICAL BALLS OF ENERGY", CN = "红色的能量球"}),
		SHOPLOCKER = en_zh({EN = "FUNCTION SELL_MORE_MEATSACK()", CN = "启动函数：多卖点肉体()"}),
	},
}
--[[
STRINGS.ACTIONS.PORKLANDREBALANCE_REPICK = "Reincarnate"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.VORTEXEYE = "I..I don't feel so good.."
STRINGS.CHARACTERS.WILSON.DESCRIBE.VORTEXEYE = "A familiar presence?"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.VORTEXEYE = "It's cold..too cold..."
STRINGS.CHARACTERS.WENDY.DESCRIBE.VORTEXEYE = "Will this take me to Abigail?"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.VORTEXEYE = "Wolfgang does not like spooky eye."
STRINGS.CHARACTERS.WX78.DESCRIBE.VORTEXEYE = "ERROR: CANNOT PERCEIVE THROUGH THE BEYOND."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.VORTEXEYE = "This trinket somehow reminds me of the post-Vedic myths of Samsara."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.VORTEXEYE = "It looks cold, eh, Lucy?"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.VORTEXEYE = "No doubt the work of Them."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.VORTEXEYE = "The maw of Hel."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.VORTEXEYE = "It's so cold inside!"
STRINGS.CHARACTERS.WARLY.DESCRIBE.VORTEXEYE = "Maman..."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.VORTEXEYE = "So cold."
STRINGS.CHARACTERS.WINONA.DESCRIBE.VORTEXEYE = "C-charlie? Are you there?"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.VORTEXEYE = "Hyuyu! To another adventure!"
STRINGS.CHARACTERS.WALTER.DESCRIBE.VORTEXEYE = "Yeeeep. It's cursed."
STRINGS.CHARACTERS.WURT.DESCRIBE.VORTEXEYE = "Feel weeeeeeeeeeeeak..."
STRINGS.CHARACTERS.WANDA.DESCRIBE.VORTEXEYE = "It's time for Them to take me, isn't it?"]]--